const mongoos=require('mongoose');
const mongooseFieldEncryption = require("mongoose-field-encryption").fieldEncryption;
var keyString = "hpXa6pTJOWDAClC/J6POVTjvJpMIiPAMQiTMjBrcOGw=";

const DoctorSchema=new mongoos.Schema({
    docid:{
        type:String,
        require:true
    },
    fname:{
        type:String,
        require:true
    },
    mname:{
        type:String,
    },
    lname:{
        type:String,
        require:true
    },
    dob:{
        type:String,
        require:true
    },
    addrIn1:{
        type:String,
        require:true
    },
    addrIn2:{
        type:String,
        require:true
    },
    addrIn3:{
        type:String,
        require:true
    },
    addrIn4:{
        type:String,
        require:true
    },
    city:{
        type:String,
        require:true
    },
    country:{
        type:String,
        require:true
    },
    state:{
        type:String,
        require:true
    },
    zpcode:{
        type:Number,
        require:true
    },
    contdtls:{
        type:JSON,
        require:true
    },
    splzns:{
        type:JSON,
        require:true
    },
    conslttmngs:{
        type:JSON,
        require:true
    },
    practstdt:{
        type:String,
        require:true
    },
    profsumm:{
        type:String,
        require:true
    },
    actv:{
        type:String,
        require:true
    }
},{
    timestamps:true
});
DoctorSchema.plugin(mongooseFieldEncryption, { fields: ["fname","mname","lname","dob","email", "addrIn1","addrIn2","contdtls"], secret: keyString });

module.exports=mongoos.model('DoctorInfor',DoctorSchema)